services:
  dev_app:
    container_name: GeoSiteList_dev
    build: ..
    ports:
      - "5171:5173"
    command: /bin/sh -c "pnpm run dev --host"
    volumes:
      - ..:/code
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
